DROP TABLE IF EXISTS prices;

CREATE TABLE prices
(
    id            BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id      BIGINT        NOT NULL,
    product_id    BIGINT        NOT NULL,
    price_list_id BIGINT        NOT NULL,
    start_date    TIMESTAMP     NOT NULL,
    end_date      TIMESTAMP     NOT NULL,
    priority      INTEGER       NOT NULL,
    price         DECIMAL(10, 2) NOT NULL,
    currency      VARCHAR(3)    NOT NULL,

    CONSTRAINT chk_prices_period CHECK (end_date >= start_date),
    CONSTRAINT chk_prices_amount CHECK (price >= 0)
);

CREATE INDEX idx_prices_lookup ON prices (brand_id, product_id, end_date, start_date);